### ISSUE TITLE
Ardite Chunks

### ISSUE THREAD

**Issue by tloskpd** [avidgamer5918/Staged-Learning#10]
I noticed you created custom content for Ardite to be broken down in the grinder/sluice setup but only allowed it to be smelted in a furnace unlike cobalt (that is integrated into magneticraft) that the cleaned chunks can be melted down in the smeltery.  Would appreciate the same functionality with ardite.

**Comment by avidgamer5918** [comment]
Thank you for pointing this out. I will add that feature in the next update
