### ISSUE TITLE
Blast Furnace quest not working

### ISSUE THREAD

**Issue by Biopticrizzl** [avidgamer5918/Staged-Learning#2]
I have everything to complete the blast furnace quest but the Quest Tab is not registering it, maybe an oredict thing, but I am not sure.
![bf quest](https://user-images.githubusercontent.com/53547521/62682466-3ce86780-b98a-11e9-88e6-c1ad0227b7d0.png)

**Comment by avidgamer5918** [comment]
Fixed in current version
