### ISSUE TITLE
Tech Reborn Plate Bending Machine removing recipes not working

### ISSUE THREAD

**Issue by kalecgos13** [avidgamer5918/Staged-Learning#22]
The techReborn PBM (Plate Bending Machine) recipes, that are removed, are only removed in JEI and not the recipe itself. This causes the thermal foundation plate recipes to not work in the PBM. 

A fix for this would be to use oreDictionary for recipes (e.q <ore:plateIron>).

**Comment by avidgamer5918** [comment]
Thank you for reporting this but unfortunately, the plate bending machine does not have CraftTweaker support so there is no way I can fix it to make it so you get the Thermal Foundation plates. All the recipes that require plates should be oredicted, If you find one that is not please let me know.

**Comment by avidgamer5918** [comment]
It seems that it does have ct support it just does not seem to be working. I submitted a bug report on Techreborn's issue tracker. Hopefully, it will get fixed soon.
