### ISSUE TITLE
Tech Reborn Industrial Grinder

### ISSUE THREAD

**Issue by Yabdat** [avidgamer5918/Staged-Learning#6]
Some of 'small pile of ** Dust' from the Industrial Grinder (Tech Reborn) has no crafting recipie from small dust to dust. 

Some of them you can smelt to ingots in the Blast Furnance, others must be smelted in the Tinkerers Smeltery.

Is it intented? Its somewhat annoying.

**Comment by avidgamer5918** [comment]
I will look into this. Thank you for reporting it.
